# Generated by Django 3.2.25 on 2025-07-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='location_city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='location_country',
        ),
    ]
